FROM nvidia/cuda:11.4.3-cudnn8-devel-ubuntu18.04

ENV LANG=C.UTF-8

RUN apt-get update -y && apt-get install -y \
    git \
    wget \
    curl \
    cmake \
    unzip \
    software-properties-common \
    unixodbc-dev \
    gcc \
    g++

RUN apt-get update
RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        software-properties-common \
    && add-apt-repository -y ppa:deadsnakes \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3.8-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && :

RUN python3.8 -m venv /venv
ENV PATH=/venv/bin:$PATH

RUN pip3 install torch torchvision torchaudio

COPY legal-prompt /home/legal-prompt
WORKDIR /home/legal-prompt/
RUN cd /home/legal-prompt/
RUN pip install -r requirements.txt

ENTRYPOINT ["python","-m", "experiments.falcon"]
