FROM damithpremasiri/python-39-base-docker:latest

COPY legal-prompt /home/legal-prompt
WORKDIR /home/legal-prompt/
RUN cd /home/legal-prompt/
RUN pip install -r requirements.txt

ENTRYPOINT ["python","-m", "experiments.falcon"]
